sudo: required
services: 
  - docker

before_install:
  - docker build -t jayboo876/react_web -f Dockerfile.dev .

script:
  - docker run -e CI=true jayboo876/react_web npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "web-app"
  env: "Web-app-env"
  bucket_name: "elasticbeanstalk-us-east-1-575311930892"
  bucket_path: "web-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"