version: '3'  # Its good practice to update version numbers
services:
  app:  # Just a random name given to the container
    build:  # To specify a non standard Dockerfile name two peicees of data are added
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'